name: Run Selenium Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest --alluredir=reports/allure-results --html=reports/allure-report.html --junitxml=reports/junit.xml

    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-results

    - name: Upload HTML Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: reports/report.html

